In [5]:
# Naive Bayes Classification

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd


In [6]:
# Importing the dataset
dataset = pd.read_csv(r'''C:\Users\USER\Documents\GitHub\Iris-Flowers-Classification-ML-Project\iris.csv''')


In [7]:
#the first five values inside the dataset
dataset.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [8]:
#Spliting the dataset into a set of independent variables and a dependent variable
X = dataset.iloc[:,:4].values
y = dataset['species'].values

In [9]:
# Splitting the dataset into training set and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 82)

In [10]:
# Feature Scaling 
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# Fitting the Naive Bayes Kernel (with linear kernel)
from sklearn.naive_bayes import GaussianNB
nvclassifier = GaussianNB()
nvclassifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [12]:
# Predicting the Test set results
y_pred = nvclassifier.predict(X_test)
print(y_pred)

['virginica' 'virginica' 'setosa' 'setosa' 'setosa' 'virginica'
 'versicolor' 'versicolor' 'versicolor' 'versicolor' 'versicolor'
 'virginica' 'setosa' 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'versicolor' 'virginica' 'setosa' 'virginica' 'versicolor']


In [13]:
#comparing the actual value and the predicted value
y_compare = np.vstack((y_test,y_pred)).T
#The first 5 values. 
y_compare[:5,:]

array([['virginica', 'virginica'],
       ['virginica', 'virginica'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa'],
       ['setosa', 'setosa']], dtype=object)

In [14]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[11  0  0]
 [ 0  8  1]
 [ 0  1  9]]


In [15]:
#finding accuracy from the confusion matrix.
x = cm.shape
right_pred = 0
wrong_pred= 0

#the diagonal elements in the confusion matrix represent the correct predictions
for row in range(x[0]):
    for col in range(x[1]):
        if row == col:
            right_pred +=cm[row,col]
        else:
            wrong_pred += cm[row,col]
print('No. of Accurate predictions: ', right_pred)
print('No. of False predictions:', wrong_pred)
print ('\nAccuracy of the Naive Bayes Clasification Model: ', right_pred/(cm.sum()))

No. of Accurate predictions:  28
No. of False predictions: 2

Accuracy of the Naive Bayes Clasification Model:  0.9333333333333333
